.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "MDSTART" "1" "February 2021" ""
.SH "NAME"
\fBmdstart\fR \- Locally view markdown files in a browser
.SH "SYNOPSIS"
.nf
mdstart [options] [<file\.md>]
.fi
.SH "DESCRIPTION"
Starts a local server to render "markdown" files within your browser:
.IP "\[ci]" 4
Runs on \fBlocalhost:4000\fR
.IP "\[ci]" 4
Supports Markdown Syntax \fIhttp://daringfireball\.net/projects/markdown/syntax\fR
.br
with GFM \fIhttps://help\.github\.com/articles/github\-flavored\-markdown\fR\.
.IP "\[ci]" 4
Markdown rendering based on markdown\-it \fIhttps://github\.com/markdown\-it/markdown\-it\fR\.
.br
Enabled Plugins for: Emojis, Task lists, Footnotes, KaTeX \fIhttps://katex\.org/\fR
.IP "\[ci]" 4
Includes markedpp \fIhttps://github\.com/commenthol/markedpp\fR as preprocessor\.
.IP "\[ci]" 4
Supports syntax highlighting using highlight\.js \fIhttp://highlightjs\.org\fR
.IP "\[ci]" 4
For supported markdown syntax see the Cheatsheet\.
.IP "\[ci]" 4
Automatic update in browser after saving edited file\. (Tested on Linux, MacOS, Windows)
.IP "" 0
.SH "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help and exit\.
.TP
\fB\-\-version\fR
Output version information and exit\.
.TP
\fB\-p\fR, \fB\-\-port\fR \fB<number=4000>\fR
Change the default port of the server\. Default is 4000\.
.TP
\fB\-b\fR, \fB\-\-browser\fR \fB<exe>\fR
Use a different browser executable\.
.TP
\fB\-c\fR, \fB\-\-confluence\fR
Generate confluence html\. Copy and paste the rendered output into a editor window at confluence\. Images need manual upload\.
.SH "EXAMPLES"
Start the server:
.IP "" 4
.nf
mdstart
.fi
.IP "" 0
.P
Open a document in the default browser:
.IP "" 4
.nf
mdstart README\.md
.fi
.IP "" 0
.P
Open the configuration page:
.IP "" 4
.nf
mdstart /config
.fi
.IP "" 0
.P
Open my home directory:
.IP "" 4
.nf
mdstart /
.fi
.IP "" 0
.P
Open the cheatsheet:
.IP "" 4
.nf
mdstart /cheatsheet
.fi
.IP "" 0
.P
Start with a different browser on port 2000:
.IP "" 4
.nf
mdstart \-p 2000 \-b firefox
.fi
.IP "" 0
.SH "INSTALLATION"
.nf
npm i \-g md\-fileserver
.fi
.SH "COPYRIGHT"
Copyright (c) 2014\- commenthol \- MIT License
.SH "REPORTING BUGS"
md\-fileserver repository \fIhttps://github\.com/commenthol/md\-fileserver/issues\fR
